#!/usr/bin/env python3
"""
Minimal Foundry compiler CLI.

Reads a Foundry Definition (YAML or JSON) and generates a minimal plugin skeleton
with manifest.yaml and compliance-proof-template.json. The compiler enforces
that constitution references are present and refuses to generate otherwise.

This script is intentionally small and produces no business logic.
"""

import argparse
import json
import os
import sys
from datetime import datetime

try:
    import yaml
    YAML_AVAILABLE = True
except Exception:
    YAML_AVAILABLE = False


REQUIRED_CONST_REF_PATHS = [
    ("required_constitution_refs", "business_constitution_ref"),
    ("required_constitution_refs", "engineering_constitution_ref"),
]


def load_definition(path):
    with open(path, "r", encoding="utf-8") as f:
        data = f.read()
    if path.lower().endswith(".json"):
        return json.loads(data)
    if YAML_AVAILABLE:
        return yaml.safe_load(data)
    # Fallback: try a naive YAML-like parse for the minimal example (not robust)
    try:
        return json.loads(data)
    except Exception:
        print("PyYAML is not installed and input is not JSON. Please install pyyaml or provide JSON.")
        sys.exit(2)


def check_constitution_refs(defn):
    missing = []
    for *_, key in REQUIRED_CONST_REF_PATHS:
        node = defn
        # support nested access
        for p in ("required_constitution_refs",):
            if p not in defn:
                missing.append("required_constitution_refs")
                break
        # explicit checks
        if "required_constitution_refs" not in defn:
            break
        refs = defn.get("required_constitution_refs", {})
        if "business_constitution_ref" not in refs:
            missing.append("business_constitution_ref")
        if "engineering_constitution_ref" not in refs:
            missing.append("engineering_constitution_ref")
        break
    return sorted(set(missing))


def ensure_dir(path):
    os.makedirs(path, exist_ok=True)


def write_file(path, content):
    with open(path, "w", encoding="utf-8") as f:
        f.write(content)


def generate_manifest(defn, out_path, generator_version="0.1.0"):
    manifest = {
        "plugin_id": defn.get("id"),
        "name": defn.get("name"),
        "version": defn.get("version", "0.0.0"),
        "declared_contracts": defn.get("required_contracts", []),
        "outputs": defn.get("outputs", []),
        "constitution_refs": defn.get("required_constitution_refs", {}),
        "generator_version": generator_version,
        "generated_at": datetime.utcnow().isoformat() + "Z",
        "contact": defn.get("contact", "<owner@example.com>"),
    }
    # Write manifest.yaml as a minimal YAML-like file without pyyaml dependency
    lines = []
    for k, v in manifest.items():
        if isinstance(v, (list, dict)):
            lines.append(f"{k}:")
            if isinstance(v, list):
                for item in v:
                    lines.append(f"  - {item}")
            else:
                for kk, vv in v.items():
                    lines.append(f"  {kk}: {vv}")
        else:
            lines.append(f"{k}: {v}")
    content = "\n".join(lines) + "\n"
    write_file(os.path.join(out_path, "manifest.yaml"), content)


def generate_compliance_proof_template(defn, out_path):
    proof = {
        "proof_id": f"proof-{defn.get('id')}-{datetime.utcnow().strftime('%Y%m%dT%H%M%SZ')}",
        "plugin_id": defn.get("id"),
        "manifest_ref": "manifest.yaml",
        "test_suite_refs": [],
        "human_approvals": [],
        "referenced_constitution_revisions": defn.get("required_constitution_refs", {}),
        "signature": None,
    }
    write_file(os.path.join(out_path, "compliance-proof-template.json"), json.dumps(proof, indent=2))


def generate_readme(defn, out_path):
    lines = []
    lines.append(f"# {defn.get('name')}")
    lines.append("")
    lines.append(defn.get("short_description", "No description provided."))
    lines.append("")
    lines.append("Constitutional references:")
    refs = defn.get("required_constitution_refs", {})
    for k, v in refs.items():
        lines.append(f"- {k}: {v}")
    lines.append("")
    lines.append("This plugin skeleton was generated by the Foundry compiler. It contains no business logic and must be completed by the plugin author.")
    write_file(os.path.join(out_path, "README.md"), "\n".join(lines) + "\n")


def generate_placeholder_tests(out_path):
    ensure_dir(os.path.join(out_path, "tests"))
    write_file(os.path.join(out_path, "tests", "example_test_placeholder.txt"), "# Add unit tests for manifest and compliance proofs here\n")


def run(def_path, out_dir):
    defn = load_definition(def_path)
    missing = check_constitution_refs(defn)
    if missing:
        print("Error: Missing required constitution references:", ", ".join(missing))
        sys.exit(3)

    plugin_id = defn.get("id")
    if not plugin_id:
        print("Error: Foundry Definition must include an 'id' field.")
        sys.exit(4)

    plugin_dir = os.path.join(out_dir, plugin_id)
    ensure_dir(plugin_dir)

    generate_readme(defn, plugin_dir)
    generate_manifest(defn, plugin_dir)
    generate_compliance_proof_template(defn, plugin_dir)
    generate_placeholder_tests(plugin_dir)

    # create docs/TRACEABILITY.md
    ensure_dir(os.path.join(plugin_dir, "docs"))
    trace_lines = [
        "# Traceability",
        "",
        "This file lists the constitutional references and where to find related artifacts.",
        "",
        "Constitution references:",
    ]
    refs = defn.get("required_constitution_refs", {})
    for k, v in refs.items():
        trace_lines.append(f"- {k}: {v}")
    write_file(os.path.join(plugin_dir, "docs", "TRACEABILITY.md"), "\n".join(trace_lines) + "\n")

    print(f"Generated plugin skeleton at: {plugin_dir}")


def main():
    parser = argparse.ArgumentParser(description="Foundry minimal compiler CLI")
    parser.add_argument("definition", help="Path to Foundry definition (YAML or JSON)")
    parser.add_argument("--out-dir", default="generated_example", help="Output directory for generated skeleton")
    args = parser.parse_args()
    run(args.definition, args.out_dir)


if __name__ == "__main__":
    main()
